version: '3'

services:
  db:
    restart: always
    image: mysql:5.6
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'myproject'
       MYSQL_USER: 'myprojectuser'
       MYSQL_PASSWORD: 'Root@123mysqlmyproject'
       MYSQL_ROOT_PASSWORD: 'Root@123mysql'

    volumes:
      - "db_data_1:/var/lib/mysql/data"
    networks:
      - todo_network

  web:
    build: .
    tty : true
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /my_app_dir
    networks:
      - todo_network
    command: bash -lc "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data_1:
    external: true


networks:
  todo_network:
    driver: bridge
